# Generated by Django 2.2.5 on 2021-01-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Software Developer', 'Software Developer'), ('Project Manager', 'Project Manager'), ('Team Lead ', 'Team Lead'), ('System Engineer', 'System Engineer'), ('Marketing Head', 'Marketing Head')], default='Software Developer', max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
