# Generated by Django 3.1.5 on 2021-01-23 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Software Developer', 'Software Developer'), ('Project Manager', 'Project Manager'), ('Team Lead ', 'Team Lead'), ('System Engineer', 'System Engineer'), ('Marketing Head', 'Marketing Head')], default='Software Developer', max_length=100, unique=True),
        ),
    ]
