# Generated by Django 3.1.5 on 2021-01-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.ManyToManyField(blank=True, to='taskapp.Comments'),
        ),
    ]
